<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title> Spotify APP</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="<?php echo APP_PATH . '/views/mystyle.css' ?>">
</head>
<style>
  body {
    font-family: Arial;
  }

  * {
    box-sizing: border-box;
  }

  form.example input[type=text] {
    padding: 10px;
    font-size: 17px;
    border: 1px solid grey;
    float: left;
    width: 80%;
    background: #f1f1f1;
  }

  form.example button {
    float: left;
    width: 20%;
    padding: 10px;
    background: #2196F3;
    color: white;
    font-size: 17px;
    border: 1px solid grey;
    border-left: none;
    cursor: pointer;
  }

  form.example button:hover {
    background: #0b7dda;
  }

  form.example::after {
    content: "";
    clear: both;
    display: table;
  }
</style>

<body>
  <div class="container">

    <?php if ($this->cookies->has("login-action")) {
      echo $this->tag->linkTo(
        [
          '/index/logOut',
          'Logout',
          'class' => 'btn btn-outline-success my-2 my-sm-0'
        ]
      );
    } ?>


    <?php if ($this->cookies->has("login-action")) {
      echo $this->tag->linkTo(
        [
          '/playlist',
          'Playlist',
          'class' => 'btn btn-outline-success my-2 my-sm-0'
        ]
      );
    } ?>
    <?php if ($this->cookies->has("login-action")) {
      echo $this->tag->linkTo(
        [
          '/',
          'Search',
          'class' => 'btn btn-outline-success my-2 my-sm-0'
        ]
      );
    } ?>
    <?php echo $this->getContent(); ?>
  </div>
</body>

</html>